  <!-- create footer -->
    <div class="footer">
      <h1>Contact Us</h1>
      <!-- create horizontal list and add icons -->
      <ul class="ul_top_hypers">
        <li>
          <a href="https://www.instagram.com" class="ul_icon" target="_blank"><i class="fab fa-instagram"></i> Instagram</a>
        </li>
        <li>
          <a href="https://www.linkedin.com" class="ul_icon" target="_blank"><i class="fab fa-linkedin"></i> LinkedIn</a>
        </li>
        <li>
          <a href="https://www.facebook.com" class="ul_icon" target="_blank"><i class="fab fa-facebook"></i> Facebook</a>
        </li>
      </ul>
    </div>
  </div>
