  <!-- create footer -->
    <div class="footer">
      <h1>Contact Us</h1>
      <!-- create horizontal list and add icons -->
      <ul class="ul_top_hypers">
        <li>
          <a href="" class="ul_icon" target="_blank"><i class="fab fa-instagram"></i></a>
        </li>
        <li>
          <a href="" class="ul_icon" target="_blank"><i class="fab fa-linkedin"></i></a>
        </li>
        <li>
          <a href="" class="ul_icon" target="_blank"><i class="fab fa-facebook"></i></a>
        </li>
      </ul>
    </div>
  </div>
