    <!-- create header -->
    <div class="header">
      <div class="header-text">
        <h1>IT Hiring Solutions</h1>
        <!-- create lava animation enhancement -->
        <div class="lamp">
          <div class="glass">
            <div class="lava">
              <div class="blob"></div>
              <div class="blob"></div>
              <div class="blob"></div>
              <div class="blob top"></div>
              <div class="blob bottom"></div>
            </div>
          </div>
        </div>
      </div>
      <!-- span for clock digits and to allow JS function to append -->
      <span id="clock"></span>
      <script src="./scripts/enhancements.js"></script>
    </div>
