<!-- create navbar -->
<div class="topnav">
  <a href="./index.php"><strong>Home</strong></a>
  <a href="./jobs.php">Jobs</a>
  <a href="./apply.php">Apply</a>
  <a href="./about.php">About</a>
  <a href="./enhancements.php">Enhancements</a>
  <a href="./enhancements2.php">Enhancements 2</a>
  <a href="./phpenhancements.php">Enhancements 3</a>
  <a href="./manage.php">Manage</a>
  <a href="./upload.php">Upload</a>
</div>
